"""
AI-generated database of all pokemon

Something may be wrong, some stuff was already fixed by hand
"""

from __future__ import annotations

from ._types import Species, Type

families: list[list[Species]] = [
    [
        Species(1, "bulbasaur", Type.grass, Type.poison),
        Species(2, "ivysaur", Type.grass, Type.poison),
        Species(3, "venusaur", Type.grass, Type.poison),
    ],
    [
        Species(4, "charmander", Type.fire),
        Species(5, "charmeleon", Type.fire),
        Species(6, "charizard", Type.fire, Type.flying),
    ],
    [
        Species(7, "squirtle", Type.water),
        Species(8, "wartortle", Type.water),
        Species(9, "blastoise", Type.water),
    ],
    [
        Species(10, "caterpie", Type.bug),
        Species(11, "metapod", Type.bug),
        Species(12, "butterfree", Type.bug, Type.flying),
    ],
    [
        Species(13, "weedle", Type.bug, Type.poison),
        Species(14, "kakuna", Type.bug, Type.poison),
        Species(15, "beedrill", Type.bug, Type.poison),
    ],
    [
        Species(16, "pidgey", Type.normal, Type.flying),
        Species(17, "pidgeotto", Type.normal, Type.flying),
        Species(18, "pidgeot", Type.normal, Type.flying),
    ],
    [Species(19, "rattata", Type.normal), Species(20, "raticate", Type.normal)],
    [
        Species(21, "spearow", Type.normal, Type.flying),
        Species(22, "fearow", Type.normal, Type.flying),
    ],
    [Species(23, "ekans", Type.poison), Species(24, "arbok", Type.poison)],
    [
        Species(25, "pikachu", Type.electric),
        Species(26, "raichu", Type.electric),
        Species(172, "pichu", Type.electric),
    ],
    [Species(27, "sandshrew", Type.ground), Species(28, "sandslash", Type.ground)],
    [
        Species(29, "nidoran-f", Type.poison),
        Species(30, "nidorina", Type.poison),
        Species(31, "nidoqueen", Type.poison, Type.ground),
    ],
    [
        Species(32, "nidoran-m", Type.poison),
        Species(33, "nidorino", Type.poison),
        Species(34, "nidoking", Type.poison, Type.ground),
    ],
    [
        Species(35, "clefairy", Type.fairy),
        Species(36, "clefable", Type.fairy),
        Species(173, "cleffa", Type.fairy),
    ],
    [Species(37, "vulpix", Type.fire), Species(38, "ninetales", Type.fire)],
    [
        Species(39, "jigglypuff", Type.normal, Type.fairy),
        Species(40, "wigglytuff", Type.normal, Type.fairy),
        Species(174, "igglybuff", Type.normal, Type.fairy),
    ],
    [
        Species(41, "zubat", Type.poison, Type.flying),
        Species(42, "golbat", Type.poison, Type.flying),
        Species(169, "crobat", Type.poison, Type.flying),
    ],
    [
        Species(43, "oddish", Type.grass, Type.poison),
        Species(44, "gloom", Type.grass, Type.poison),
        Species(45, "vileplume", Type.grass, Type.poison),
        Species(182, "bellossom", Type.grass),
    ],
    [
        Species(46, "paras", Type.bug, Type.grass),
        Species(47, "parasect", Type.bug, Type.grass),
    ],
    [
        Species(48, "venonat", Type.bug, Type.poison),
        Species(49, "venomoth", Type.bug, Type.poison),
    ],
    [Species(50, "diglett", Type.ground), Species(51, "dugtrio", Type.ground)],
    [
        Species(52, "meowth", Type.normal),
        Species(53, "persian", Type.normal),
        Species(863, "perrserker", Type.steel),
    ],
    [Species(54, "psyduck", Type.water), Species(55, "golduck", Type.water)],
    [
        Species(56, "mankey", Type.fighting),
        Species(57, "primeape", Type.fighting),
        Species(979, "annihilape", Type.fighting, Type.ghost),
    ],
    [Species(58, "growlithe", Type.fire), Species(59, "arcanine", Type.fire)],
    [
        Species(60, "poliwag", Type.water),
        Species(61, "poliwhirl", Type.water),
        Species(62, "poliwrath", Type.water, Type.fighting),
        Species(186, "politoed", Type.water),
    ],
    [
        Species(63, "abra", Type.psychic),
        Species(64, "kadabra", Type.psychic),
        Species(65, "alakazam", Type.psychic),
    ],
    [
        Species(66, "machop", Type.fighting),
        Species(67, "machoke", Type.fighting),
        Species(68, "machamp", Type.fighting),
    ],
    [
        Species(69, "bellsprout", Type.grass, Type.poison),
        Species(70, "weepinbell", Type.grass, Type.poison),
        Species(71, "victreebel", Type.grass, Type.poison),
    ],
    [
        Species(72, "tentacool", Type.water, Type.poison),
        Species(73, "tentacruel", Type.water, Type.poison),
    ],
    [
        Species(74, "geodude", Type.rock, Type.ground),
        Species(75, "graveler", Type.rock, Type.ground),
        Species(76, "golem", Type.rock, Type.ground),
    ],
    [Species(77, "ponyta", Type.fire), Species(78, "rapidash", Type.fire)],
    [
        Species(79, "slowpoke", Type.water, Type.psychic),
        Species(80, "slowbro", Type.water, Type.psychic),
        Species(199, "slowking", Type.water, Type.psychic),
    ],
    [
        Species(81, "magnemite", Type.electric, Type.steel),
        Species(82, "magneton", Type.electric, Type.steel),
        Species(462, "magnezone", Type.electric, Type.steel),
    ],
    [
        Species(83, "farfetch'd", Type.normal, Type.flying),
        Species(865, "sirfetch'd", Type.fighting),
    ],
    [
        Species(84, "doduo", Type.normal, Type.flying),
        Species(85, "dodrio", Type.normal, Type.flying),
    ],
    [Species(86, "seel", Type.water), Species(87, "dewgong", Type.water, Type.ice)],
    [Species(88, "grimer", Type.poison), Species(89, "muk", Type.poison)],
    [
        Species(90, "shellder", Type.water),
        Species(91, "cloyster", Type.water, Type.ice),
    ],
    [
        Species(92, "gastly", Type.ghost, Type.poison),
        Species(93, "haunter", Type.ghost, Type.poison),
        Species(94, "gengar", Type.ghost, Type.poison),
    ],
    [
        Species(95, "onix", Type.rock, Type.ground),
        Species(208, "steelix", Type.steel, Type.ground),
    ],
    [Species(96, "drowzee", Type.psychic), Species(97, "hypno", Type.psychic)],
    [Species(98, "krabby", Type.water), Species(99, "kingler", Type.water)],
    [Species(100, "voltorb", Type.electric), Species(101, "electrode", Type.electric)],
    [
        Species(102, "exeggcute", Type.grass, Type.psychic),
        Species(103, "exeggutor", Type.grass, Type.psychic),
    ],
    [Species(104, "cubone", Type.ground), Species(105, "marowak", Type.ground)],
    [
        Species(106, "hitmonlee", Type.fighting),
        Species(107, "hitmonchan", Type.fighting),
        Species(236, "tyrogue", Type.fighting),
        Species(237, "hitmontop", Type.fighting),
    ],
    [Species(108, "lickitung", Type.normal), Species(463, "lickilicky", Type.normal)],
    [Species(109, "koffing", Type.poison), Species(110, "weezing", Type.poison)],
    [
        Species(111, "rhyhorn", Type.ground, Type.rock),
        Species(112, "rhydon", Type.ground, Type.rock),
        Species(464, "rhyperior", Type.ground, Type.rock),
    ],
    [
        Species(113, "chansey", Type.normal),
        Species(242, "blissey", Type.normal),
        Species(440, "happiny", Type.normal),
    ],
    [Species(114, "tangela", Type.grass), Species(465, "tangrowth", Type.grass)],
    [Species(115, "kangaskhan", Type.normal)],
    [
        Species(116, "horsea", Type.water),
        Species(117, "seadra", Type.water),
        Species(230, "kingdra", Type.water, Type.dragon),
    ],
    [Species(118, "goldeen", Type.water), Species(119, "seaking", Type.water)],
    [
        Species(120, "staryu", Type.water),
        Species(121, "starmie", Type.water, Type.psychic),
    ],
    [
        Species(122, "mr-mime", Type.psychic, Type.fairy),
        Species(439, "mime-jr", Type.psychic, Type.fairy),
        Species(866, "mr-rime", Type.ice, Type.psychic),
    ],
    [
        Species(123, "scyther", Type.bug, Type.flying),
        Species(212, "scizor", Type.bug, Type.steel),
        Species(900, "kleavor", Type.bug, Type.rock),
    ],
    [
        Species(124, "jynx", Type.ice, Type.psychic),
        Species(238, "smoochum", Type.ice, Type.psychic),
    ],
    [
        Species(125, "electabuzz", Type.electric),
        Species(239, "elekid", Type.electric),
        Species(466, "electivire", Type.electric),
    ],
    [
        Species(126, "magmar", Type.fire),
        Species(240, "magby", Type.fire),
        Species(467, "magmortar", Type.fire),
    ],
    [Species(127, "pinsir", Type.bug)],
    [Species(128, "tauros", Type.normal)],
    [
        Species(129, "magikarp", Type.water),
        Species(130, "gyarados", Type.water, Type.flying),
    ],
    [Species(131, "lapras", Type.water, Type.ice)],
    [Species(132, "ditto", Type.normal)],
    [
        Species(133, "eevee", Type.normal),
        Species(134, "vaporeon", Type.water),
        Species(135, "jolteon", Type.electric),
        Species(136, "flareon", Type.fire),
        Species(196, "espeon", Type.psychic),
        Species(197, "umbreon", Type.dark),
        Species(470, "leafeon", Type.grass),
        Species(471, "glaceon", Type.ice),
        Species(700, "sylveon", Type.fairy),
    ],
    [
        Species(137, "porygon", Type.normal),
        Species(233, "porygon2", Type.normal),
        Species(474, "porygon-z", Type.normal),
    ],
    [
        Species(138, "omanyte", Type.rock, Type.water),
        Species(139, "omastar", Type.rock, Type.water),
    ],
    [
        Species(140, "kabuto", Type.rock, Type.water),
        Species(141, "kabutops", Type.rock, Type.water),
    ],
    [Species(142, "aerodactyl", Type.rock, Type.flying)],
    [Species(143, "snorlax", Type.normal), Species(446, "munchlax", Type.normal)],
    [Species(144, "articuno", Type.ice, Type.flying)],
    [Species(145, "zapdos", Type.electric, Type.flying)],
    [Species(146, "moltres", Type.fire, Type.flying)],
    [
        Species(147, "dratini", Type.dragon),
        Species(148, "dragonair", Type.dragon),
        Species(149, "dragonite", Type.dragon, Type.flying),
    ],
    [Species(150, "mewtwo", Type.psychic)],
    [Species(151, "mew", Type.psychic)],
    [
        Species(152, "chikorita", Type.grass),
        Species(153, "bayleef", Type.grass),
        Species(154, "meganium", Type.grass),
    ],
    [
        Species(155, "cyndaquil", Type.fire),
        Species(156, "quilava", Type.fire),
        Species(157, "typhlosion", Type.fire),
    ],
    [
        Species(158, "totodile", Type.water),
        Species(159, "croconaw", Type.water),
        Species(160, "feraligatr", Type.water),
    ],
    [Species(161, "sentret", Type.normal), Species(162, "furret", Type.normal)],
    [
        Species(163, "hoothoot", Type.normal, Type.flying),
        Species(164, "noctowl", Type.normal, Type.flying),
    ],
    [
        Species(165, "ledyba", Type.bug, Type.flying),
        Species(166, "ledian", Type.bug, Type.flying),
    ],
    [
        Species(167, "spinarak", Type.bug, Type.poison),
        Species(168, "ariados", Type.bug, Type.poison),
    ],
    [
        Species(170, "chinchou", Type.water, Type.electric),
        Species(171, "lanturn", Type.water, Type.electric),
    ],
    [
        Species(175, "togepi", Type.fairy),
        Species(176, "togetic", Type.fairy, Type.flying),
        Species(468, "togekiss", Type.fairy, Type.flying),
    ],
    [
        Species(177, "natu", Type.psychic, Type.flying),
        Species(178, "xatu", Type.psychic, Type.flying),
    ],
    [
        Species(179, "mareep", Type.electric),
        Species(180, "flaaffy", Type.electric),
        Species(181, "ampharos", Type.electric),
    ],
    [
        Species(183, "marill", Type.water, Type.fairy),
        Species(184, "azumarill", Type.water, Type.fairy),
        Species(298, "azurill", Type.normal, Type.fairy),
    ],
    [Species(185, "sudowoodo", Type.rock), Species(438, "bonsly", Type.rock)],
    [
        Species(187, "hoppip", Type.grass, Type.flying),
        Species(188, "skiploom", Type.grass, Type.flying),
        Species(189, "jumpluff", Type.grass, Type.flying),
    ],
    [Species(190, "aipom", Type.normal), Species(424, "ambipom", Type.normal)],
    [Species(191, "sunkern", Type.grass), Species(192, "sunflora", Type.grass)],
    [
        Species(193, "yanma", Type.bug, Type.flying),
        Species(469, "yanmega", Type.bug, Type.flying),
    ],
    [
        Species(194, "wooper", Type.water, Type.ground),
        Species(195, "quagsire", Type.water, Type.ground),
        Species(980, "clodsire", Type.poison, Type.ground),
    ],
    [
        Species(198, "murkrow", Type.dark, Type.flying),
        Species(430, "honchkrow", Type.dark, Type.flying),
    ],
    [Species(200, "misdreavus", Type.ghost), Species(429, "mismagius", Type.ghost)],
    [Species(201, "unown", Type.psychic)],
    [Species(202, "wobbuffet", Type.psychic), Species(360, "wynaut", Type.psychic)],
    [
        Species(203, "girafarig", Type.normal, Type.psychic),
        Species(981, "farigiraf", Type.normal, Type.psychic),
    ],
    [
        Species(204, "pineco", Type.bug),
        Species(205, "forretress", Type.bug, Type.steel),
    ],
    [Species(206, "dunsparce", Type.normal), Species(982, "dudunsparce", Type.normal)],
    [
        Species(207, "gligar", Type.ground, Type.flying),
        Species(472, "gliscor", Type.ground, Type.flying),
    ],
    [Species(209, "snubbull", Type.fairy), Species(210, "granbull", Type.fairy)],
    [
        Species(211, "qwilfish", Type.water, Type.poison),
        Species(904, "overqwil", Type.dark, Type.poison),
    ],
    [Species(213, "shuckle", Type.bug, Type.rock)],
    [Species(214, "heracross", Type.bug, Type.fighting)],
    [
        Species(215, "sneasel", Type.dark, Type.ice),
        Species(461, "weavile", Type.dark, Type.ice),
        Species(903, "sneasler", Type.fighting, Type.poison),
    ],
    [
        Species(216, "teddiursa", Type.normal),
        Species(217, "ursaring", Type.normal),
        Species(901, "ursaluna", Type.ground, Type.normal),
    ],
    [Species(218, "slugma", Type.fire), Species(219, "magcargo", Type.fire, Type.rock)],
    [
        Species(220, "swinub", Type.ice, Type.ground),
        Species(221, "piloswine", Type.ice, Type.ground),
        Species(473, "mamoswine", Type.ice, Type.ground),
    ],
    [
        Species(222, "corsola", Type.water, Type.rock),
        Species(864, "cursola", Type.ghost),
    ],
    [Species(223, "remoraid", Type.water), Species(224, "octillery", Type.water)],
    [Species(225, "delibird", Type.ice, Type.flying)],
    [
        Species(226, "mantine", Type.water, Type.flying),
        Species(458, "mantyke", Type.water, Type.flying),
    ],
    [Species(227, "skarmory", Type.steel, Type.flying)],
    [
        Species(228, "houndour", Type.dark, Type.fire),
        Species(229, "houndoom", Type.dark, Type.fire),
    ],
    [Species(231, "phanpy", Type.ground), Species(232, "donphan", Type.ground)],
    [
        Species(234, "stantler", Type.normal),
        Species(899, "wyrdeer", Type.normal, Type.psychic),
    ],
    [Species(235, "smeargle", Type.normal)],
    [Species(241, "miltank", Type.normal)],
    [Species(243, "raikou", Type.electric)],
    [Species(244, "entei", Type.fire)],
    [Species(245, "suicune", Type.water)],
    [
        Species(246, "larvitar", Type.rock, Type.ground),
        Species(247, "pupitar", Type.rock, Type.ground),
        Species(248, "tyranitar", Type.rock, Type.dark),
    ],
    [Species(249, "lugia", Type.psychic, Type.flying)],
    [Species(250, "ho-oh", Type.fire, Type.flying)],
    [Species(251, "celebi", Type.psychic, Type.grass)],
    [
        Species(252, "treecko", Type.grass),
        Species(253, "grovyle", Type.grass),
        Species(254, "sceptile", Type.grass),
    ],
    [
        Species(255, "torchic", Type.fire),
        Species(256, "combusken", Type.fire, Type.fighting),
        Species(257, "blaziken", Type.fire, Type.fighting),
    ],
    [
        Species(258, "mudkip", Type.water),
        Species(259, "marshtomp", Type.water, Type.ground),
        Species(260, "swampert", Type.water, Type.ground),
    ],
    [Species(261, "poochyena", Type.dark), Species(262, "mightyena", Type.dark)],
    [
        Species(263, "zigzagoon", Type.normal),
        Species(264, "linoone", Type.normal),
        Species(862, "obstagoon", Type.dark, Type.normal),
    ],
    [
        Species(265, "wurmple", Type.bug),
        Species(266, "silcoon", Type.bug),
        Species(267, "beautifly", Type.bug, Type.flying),
        Species(268, "cascoon", Type.bug),
        Species(269, "dustox", Type.bug, Type.poison),
    ],
    [
        Species(270, "lotad", Type.water, Type.grass),
        Species(271, "lombre", Type.water, Type.grass),
        Species(272, "ludicolo", Type.water, Type.grass),
    ],
    [
        Species(273, "seedot", Type.grass),
        Species(274, "nuzleaf", Type.grass, Type.dark),
        Species(275, "shiftry", Type.grass, Type.dark),
    ],
    [
        Species(276, "taillow", Type.normal, Type.flying),
        Species(277, "swellow", Type.normal, Type.flying),
    ],
    [
        Species(278, "wingull", Type.water, Type.flying),
        Species(279, "pelipper", Type.water, Type.flying),
    ],
    [
        Species(280, "ralts", Type.psychic, Type.fairy),
        Species(281, "kirlia", Type.psychic, Type.fairy),
        Species(282, "gardevoir", Type.psychic, Type.fairy),
        Species(475, "gallade", Type.psychic, Type.fighting),
    ],
    [
        Species(283, "surskit", Type.bug, Type.water),
        Species(284, "masquerain", Type.bug, Type.flying),
    ],
    [
        Species(285, "shroomish", Type.grass),
        Species(286, "breloom", Type.grass, Type.fighting),
    ],
    [
        Species(287, "slakoth", Type.normal),
        Species(288, "vigoroth", Type.normal),
        Species(289, "slaking", Type.normal),
    ],
    [
        Species(290, "nincada", Type.bug, Type.ground),
        Species(291, "ninjask", Type.bug, Type.flying),
        Species(292, "shedinja", Type.bug, Type.ghost),
    ],
    [
        Species(293, "whismur", Type.normal),
        Species(294, "loudred", Type.normal),
        Species(295, "exploud", Type.normal),
    ],
    [Species(296, "makuhita", Type.fighting), Species(297, "hariyama", Type.fighting)],
    [
        Species(299, "nosepass", Type.rock),
        Species(476, "probopass", Type.rock, Type.steel),
    ],
    [Species(300, "skitty", Type.normal), Species(301, "delcatty", Type.normal)],
    [Species(302, "sableye", Type.dark, Type.ghost)],
    [Species(303, "mawile", Type.steel, Type.fairy)],
    [
        Species(304, "aron", Type.steel, Type.rock),
        Species(305, "lairon", Type.steel, Type.rock),
        Species(306, "aggron", Type.steel, Type.rock),
    ],
    [
        Species(307, "meditite", Type.fighting, Type.psychic),
        Species(308, "medicham", Type.fighting, Type.psychic),
    ],
    [
        Species(309, "electrike", Type.electric),
        Species(310, "manectric", Type.electric),
    ],
    [Species(311, "plusle", Type.electric)],
    [Species(312, "minun", Type.electric)],
    [Species(313, "volbeat", Type.bug)],
    [Species(314, "illumise", Type.bug)],
    [
        Species(315, "roselia", Type.grass, Type.poison),
        Species(406, "budew", Type.grass, Type.poison),
        Species(407, "roserade", Type.grass, Type.poison),
    ],
    [Species(316, "gulpin", Type.poison), Species(317, "swalot", Type.poison)],
    [
        Species(318, "carvanha", Type.water, Type.dark),
        Species(319, "sharpedo", Type.water, Type.dark),
    ],
    [Species(320, "wailmer", Type.water), Species(321, "wailord", Type.water)],
    [
        Species(322, "numel", Type.fire, Type.ground),
        Species(323, "camerupt", Type.fire, Type.ground),
    ],
    [Species(324, "torkoal", Type.fire)],
    [Species(325, "spoink", Type.psychic), Species(326, "grumpig", Type.psychic)],
    [Species(327, "spinda", Type.normal)],
    [
        Species(328, "trapinch", Type.ground),
        Species(329, "vibrava", Type.ground, Type.dragon),
        Species(330, "flygon", Type.ground, Type.dragon),
    ],
    [
        Species(331, "cacnea", Type.grass),
        Species(332, "cacturne", Type.grass, Type.dark),
    ],
    [
        Species(333, "swablu", Type.normal, Type.flying),
        Species(334, "altaria", Type.dragon, Type.flying),
    ],
    [Species(335, "zangoose", Type.normal)],
    [Species(336, "seviper", Type.poison)],
    [Species(337, "lunatone", Type.rock, Type.psychic)],
    [Species(338, "solrock", Type.rock, Type.psychic)],
    [
        Species(339, "barboach", Type.water, Type.ground),
        Species(340, "whiscash", Type.water, Type.ground),
    ],
    [
        Species(341, "corphish", Type.water),
        Species(342, "crawdaunt", Type.water, Type.dark),
    ],
    [
        Species(343, "baltoy", Type.ground, Type.psychic),
        Species(344, "claydol", Type.ground, Type.psychic),
    ],
    [
        Species(345, "lileep", Type.rock, Type.grass),
        Species(346, "cradily", Type.rock, Type.grass),
    ],
    [
        Species(347, "anorith", Type.rock, Type.bug),
        Species(348, "armaldo", Type.rock, Type.bug),
    ],
    [Species(349, "feebas", Type.water), Species(350, "milotic", Type.water)],
    [Species(351, "castform", Type.normal)],
    [Species(352, "kecleon", Type.normal)],
    [Species(353, "shuppet", Type.ghost), Species(354, "banette", Type.ghost)],
    [
        Species(355, "duskull", Type.ghost),
        Species(356, "dusclops", Type.ghost),
        Species(477, "dusknoir", Type.ghost),
    ],
    [Species(357, "tropius", Type.grass, Type.flying)],
    [Species(358, "chimecho", Type.psychic), Species(433, "chingling", Type.psychic)],
    [Species(359, "absol", Type.dark)],
    [
        Species(361, "snorunt", Type.ice),
        Species(362, "glalie", Type.ice),
        Species(478, "froslass", Type.ice, Type.ghost),
    ],
    [
        Species(363, "spheal", Type.ice, Type.water),
        Species(364, "sealeo", Type.ice, Type.water),
        Species(365, "walrein", Type.ice, Type.water),
    ],
    [
        Species(366, "clamperl", Type.water),
        Species(367, "huntail", Type.water),
        Species(368, "gorebyss", Type.water),
    ],
    [Species(369, "relicanth", Type.water, Type.rock)],
    [Species(370, "luvdisc", Type.water)],
    [
        Species(371, "bagon", Type.dragon),
        Species(372, "shelgon", Type.dragon),
        Species(373, "salamence", Type.dragon, Type.flying),
    ],
    [
        Species(374, "beldum", Type.steel, Type.psychic),
        Species(375, "metang", Type.steel, Type.psychic),
        Species(376, "metagross", Type.steel, Type.psychic),
    ],
    [Species(377, "regirock", Type.rock)],
    [Species(378, "regice", Type.ice)],
    [Species(379, "registeel", Type.steel)],
    [Species(380, "latias", Type.dragon, Type.psychic)],
    [Species(381, "latios", Type.dragon, Type.psychic)],
    [Species(382, "kyogre", Type.water)],
    [Species(383, "groudon", Type.ground)],
    [Species(384, "rayquaza", Type.dragon, Type.flying)],
    [Species(385, "jirachi", Type.steel, Type.psychic)],
    [Species(386, "deoxys", Type.psychic)],
    [
        Species(387, "turtwig", Type.grass),
        Species(388, "grotle", Type.grass),
        Species(389, "torterra", Type.grass, Type.ground),
    ],
    [
        Species(390, "chimchar", Type.fire),
        Species(391, "monferno", Type.fire, Type.fighting),
        Species(392, "infernape", Type.fire, Type.fighting),
    ],
    [
        Species(393, "piplup", Type.water),
        Species(394, "prinplup", Type.water),
        Species(395, "empoleon", Type.water, Type.steel),
    ],
    [
        Species(396, "starly", Type.normal, Type.flying),
        Species(397, "staravia", Type.normal, Type.flying),
        Species(398, "staraptor", Type.normal, Type.flying),
    ],
    [
        Species(399, "bidoof", Type.normal),
        Species(400, "bibarel", Type.normal, Type.water),
    ],
    [Species(401, "kricketot", Type.bug), Species(402, "kricketune", Type.bug)],
    [
        Species(403, "shinx", Type.electric),
        Species(404, "luxio", Type.electric),
        Species(405, "luxray", Type.electric),
    ],
    [Species(408, "cranidos", Type.rock), Species(409, "rampardos", Type.rock)],
    [
        Species(410, "shieldon", Type.rock, Type.steel),
        Species(411, "bastiodon", Type.rock, Type.steel),
    ],
    [
        Species(412, "burmy", Type.bug),
        Species(413, "wormadam", Type.bug, Type.grass),
        Species(414, "mothim", Type.bug, Type.flying),
    ],
    [
        Species(415, "combee", Type.bug, Type.flying),
        Species(416, "vespiquen", Type.bug, Type.flying),
    ],
    [Species(417, "pachirisu", Type.electric)],
    [Species(418, "buizel", Type.water), Species(419, "floatzel", Type.water)],
    [Species(420, "cherubi", Type.grass), Species(421, "cherrim", Type.grass)],
    [
        Species(422, "shellos", Type.water),
        Species(423, "gastrodon", Type.water, Type.ground),
    ],
    [
        Species(425, "drifloon", Type.ghost, Type.flying),
        Species(426, "drifblim", Type.ghost, Type.flying),
    ],
    [Species(427, "buneary", Type.normal), Species(428, "lopunny", Type.normal)],
    [Species(431, "glameow", Type.normal), Species(432, "purugly", Type.normal)],
    [
        Species(434, "stunky", Type.poison, Type.dark),
        Species(435, "skuntank", Type.poison, Type.dark),
    ],
    [
        Species(436, "bronzor", Type.steel, Type.psychic),
        Species(437, "bronzong", Type.steel, Type.psychic),
    ],
    [Species(441, "chatot", Type.normal, Type.flying)],
    [Species(442, "spiritomb", Type.ghost, Type.dark)],
    [
        Species(443, "gible", Type.dragon, Type.ground),
        Species(444, "gabite", Type.dragon, Type.ground),
        Species(445, "garchomp", Type.dragon, Type.ground),
    ],
    [
        Species(447, "riolu", Type.fighting),
        Species(448, "lucario", Type.fighting, Type.steel),
    ],
    [Species(449, "hippopotas", Type.ground), Species(450, "hippowdon", Type.ground)],
    [
        Species(451, "skorupi", Type.poison, Type.bug),
        Species(452, "drapion", Type.poison, Type.dark),
    ],
    [
        Species(453, "croagunk", Type.poison, Type.fighting),
        Species(454, "toxicroak", Type.poison, Type.fighting),
    ],
    [Species(455, "carnivine", Type.grass)],
    [Species(456, "finneon", Type.water), Species(457, "lumineon", Type.water)],
    [
        Species(459, "snover", Type.grass, Type.ice),
        Species(460, "abomasnow", Type.grass, Type.ice),
    ],
    [Species(479, "rotom", Type.electric, Type.ghost)],
    [Species(480, "uxie", Type.psychic)],
    [Species(481, "mesprit", Type.psychic)],
    [Species(482, "azelf", Type.psychic)],
    [Species(483, "dialga", Type.steel, Type.dragon)],
    [Species(484, "palkia", Type.water, Type.dragon)],
    [Species(485, "heatran", Type.fire, Type.steel)],
    [Species(486, "regigigas", Type.normal)],
    [Species(487, "giratina", Type.ghost, Type.dragon)],
    [Species(488, "cresselia", Type.psychic)],
    [Species(489, "phione", Type.water), Species(490, "manaphy", Type.water)],
    [Species(491, "darkrai", Type.dark)],
    [Species(492, "shaymin", Type.grass)],
    [Species(493, "arceus", Type.normal)],
    [Species(494, "victini", Type.psychic, Type.fire)],
    [
        Species(495, "snivy", Type.grass),
        Species(496, "servine", Type.grass),
        Species(497, "serperior", Type.grass),
    ],
    [
        Species(498, "tepig", Type.fire),
        Species(499, "pignite", Type.fire, Type.fighting),
        Species(500, "emboar", Type.fire, Type.fighting),
    ],
    [
        Species(501, "oshawott", Type.water),
        Species(502, "dewott", Type.water),
        Species(503, "samurott", Type.water),
    ],
    [Species(504, "patrat", Type.normal), Species(505, "watchog", Type.normal)],
    [
        Species(506, "lillipup", Type.normal),
        Species(507, "herdier", Type.normal),
        Species(508, "stoutland", Type.normal),
    ],
    [Species(509, "purrloin", Type.dark), Species(510, "liepard", Type.dark)],
    [Species(511, "pansage", Type.grass), Species(512, "simisage", Type.grass)],
    [Species(513, "pansear", Type.fire), Species(514, "simisear", Type.fire)],
    [Species(515, "panpour", Type.water), Species(516, "simipour", Type.water)],
    [Species(517, "munna", Type.psychic), Species(518, "musharna", Type.psychic)],
    [
        Species(519, "pidove", Type.normal, Type.flying),
        Species(520, "tranquill", Type.normal, Type.flying),
        Species(521, "unfezant", Type.normal, Type.flying),
    ],
    [Species(522, "blitzle", Type.electric), Species(523, "zebstrika", Type.electric)],
    [
        Species(524, "roggenrola", Type.rock),
        Species(525, "boldore", Type.rock),
        Species(526, "gigalith", Type.rock),
    ],
    [
        Species(527, "woobat", Type.psychic, Type.flying),
        Species(528, "swoobat", Type.psychic, Type.flying),
    ],
    [
        Species(529, "drilbur", Type.ground),
        Species(530, "excadrill", Type.ground, Type.steel),
    ],
    [Species(531, "audino", Type.normal)],
    [
        Species(532, "timburr", Type.fighting),
        Species(533, "gurdurr", Type.fighting),
        Species(534, "conkeldurr", Type.fighting),
    ],
    [
        Species(535, "tympole", Type.water),
        Species(536, "palpitoad", Type.water, Type.ground),
        Species(537, "seismitoad", Type.water, Type.ground),
    ],
    [Species(538, "throh", Type.fighting)],
    [Species(539, "sawk", Type.fighting)],
    [
        Species(540, "sewaddle", Type.bug, Type.grass),
        Species(541, "swadloon", Type.bug, Type.grass),
        Species(542, "leavanny", Type.bug, Type.grass),
    ],
    [
        Species(543, "venipede", Type.bug, Type.poison),
        Species(544, "whirlipede", Type.bug, Type.poison),
        Species(545, "scolipede", Type.bug, Type.poison),
    ],
    [
        Species(546, "cottonee", Type.grass, Type.fairy),
        Species(547, "whimsicott", Type.grass, Type.fairy),
    ],
    [Species(548, "petilil", Type.grass), Species(549, "lilligant", Type.grass)],
    [
        Species(550, "basculin", Type.water),
        Species(902, "basculegion", Type.water, Type.ghost),
    ],
    [
        Species(551, "sandile", Type.ground, Type.dark),
        Species(552, "krokorok", Type.ground, Type.dark),
        Species(553, "krookodile", Type.ground, Type.dark),
    ],
    [Species(554, "darumaka", Type.fire), Species(555, "darmanitan", Type.fire)],
    [Species(556, "maractus", Type.grass)],
    [
        Species(557, "dwebble", Type.bug, Type.rock),
        Species(558, "crustle", Type.bug, Type.rock),
    ],
    [
        Species(559, "scraggy", Type.dark, Type.fighting),
        Species(560, "scrafty", Type.dark, Type.fighting),
    ],
    [Species(561, "sigilyph", Type.psychic, Type.flying)],
    [
        Species(562, "yamask", Type.ghost),
        Species(563, "cofagrigus", Type.ghost),
        Species(867, "runerigus", Type.ground, Type.ghost),
    ],
    [
        Species(564, "tirtouga", Type.water, Type.rock),
        Species(565, "carracosta", Type.water, Type.rock),
    ],
    [
        Species(566, "archen", Type.rock, Type.flying),
        Species(567, "archeops", Type.rock, Type.flying),
    ],
    [Species(568, "trubbish", Type.poison), Species(569, "garbodor", Type.poison)],
    [Species(570, "zorua", Type.dark), Species(571, "zoroark", Type.dark)],
    [Species(572, "minccino", Type.normal), Species(573, "cinccino", Type.normal)],
    [
        Species(574, "gothita", Type.psychic),
        Species(575, "gothorita", Type.psychic),
        Species(576, "gothitelle", Type.psychic),
    ],
    [
        Species(577, "solosis", Type.psychic),
        Species(578, "duosion", Type.psychic),
        Species(579, "reuniclus", Type.psychic),
    ],
    [
        Species(580, "ducklett", Type.water, Type.flying),
        Species(581, "swanna", Type.water, Type.flying),
    ],
    [
        Species(582, "vanillite", Type.ice),
        Species(583, "vanillish", Type.ice),
        Species(584, "vanilluxe", Type.ice),
    ],
    [
        Species(585, "deerling", Type.normal, Type.grass),
        Species(586, "sawsbuck", Type.normal, Type.grass),
    ],
    [Species(587, "emolga", Type.electric, Type.flying)],
    [
        Species(588, "karrablast", Type.bug),
        Species(589, "escavalier", Type.bug, Type.steel),
    ],
    [
        Species(590, "foongus", Type.grass, Type.poison),
        Species(591, "amoonguss", Type.grass, Type.poison),
    ],
    [
        Species(592, "frillish", Type.water, Type.ghost),
        Species(593, "jellicent", Type.water, Type.ghost),
    ],
    [Species(594, "alomomola", Type.water)],
    [
        Species(595, "joltik", Type.bug, Type.electric),
        Species(596, "galvantula", Type.bug, Type.electric),
    ],
    [
        Species(597, "ferroseed", Type.grass, Type.steel),
        Species(598, "ferrothorn", Type.grass, Type.steel),
    ],
    [
        Species(599, "klink", Type.steel),
        Species(600, "klang", Type.steel),
        Species(601, "klinklang", Type.steel),
    ],
    [
        Species(602, "tynamo", Type.electric),
        Species(603, "eelektrik", Type.electric),
        Species(604, "eelektross", Type.electric),
    ],
    [Species(605, "elgyem", Type.psychic), Species(606, "beheeyem", Type.psychic)],
    [
        Species(607, "litwick", Type.ghost, Type.fire),
        Species(608, "lampent", Type.ghost, Type.fire),
        Species(609, "chandelure", Type.ghost, Type.fire),
    ],
    [
        Species(610, "axew", Type.dragon),
        Species(611, "fraxure", Type.dragon),
        Species(612, "haxorus", Type.dragon),
    ],
    [Species(613, "cubchoo", Type.ice), Species(614, "beartic", Type.ice)],
    [Species(615, "cryogonal", Type.ice)],
    [Species(616, "shelmet", Type.bug), Species(617, "accelgor", Type.bug)],
    [Species(618, "stunfisk", Type.ground, Type.electric)],
    [Species(619, "mienfoo", Type.fighting), Species(620, "mienshao", Type.fighting)],
    [Species(621, "druddigon", Type.dragon)],
    [
        Species(622, "golett", Type.ground, Type.ghost),
        Species(623, "golurk", Type.ground, Type.ghost),
    ],
    [
        Species(624, "pawniard", Type.dark, Type.steel),
        Species(625, "bisharp", Type.dark, Type.steel),
        Species(983, "kingambit", Type.dark, Type.steel),
    ],
    [Species(626, "bouffalant", Type.normal)],
    [
        Species(627, "rufflet", Type.normal, Type.flying),
        Species(628, "braviary", Type.normal, Type.flying),
    ],
    [
        Species(629, "vullaby", Type.dark, Type.flying),
        Species(630, "mandibuzz", Type.dark, Type.flying),
    ],
    [Species(631, "heatmor", Type.fire)],
    [Species(632, "durant", Type.bug, Type.steel)],
    [
        Species(633, "deino", Type.dark, Type.dragon),
        Species(634, "zweilous", Type.dark, Type.dragon),
        Species(635, "hydreigon", Type.dark, Type.dragon),
    ],
    [
        Species(636, "larvesta", Type.bug, Type.fire),
        Species(637, "volcarona", Type.bug, Type.fire),
    ],
    [Species(638, "cobalion", Type.steel, Type.fighting)],
    [Species(639, "terrakion", Type.rock, Type.fighting)],
    [Species(640, "virizion", Type.grass, Type.fighting)],
    [Species(641, "tornadus", Type.flying)],
    [Species(642, "thundurus", Type.electric, Type.flying)],
    [Species(643, "reshiram", Type.dragon, Type.fire)],
    [Species(644, "zekrom", Type.dragon, Type.electric)],
    [Species(645, "landorus", Type.ground, Type.flying)],
    [Species(646, "kyurem", Type.dragon, Type.ice)],
    [Species(647, "keldeo", Type.water, Type.fighting)],
    [Species(648, "meloetta", Type.normal, Type.psychic)],
    [Species(649, "genesect", Type.bug, Type.steel)],
    [
        Species(650, "chespin", Type.grass),
        Species(651, "quilladin", Type.grass),
        Species(652, "chesnaught", Type.grass, Type.fighting),
    ],
    [
        Species(653, "fennekin", Type.fire),
        Species(654, "braixen", Type.fire),
        Species(655, "delphox", Type.fire, Type.psychic),
    ],
    [
        Species(656, "froakie", Type.water),
        Species(657, "frogadier", Type.water),
        Species(658, "greninja", Type.water, Type.dark),
    ],
    [
        Species(659, "bunnelby", Type.normal),
        Species(660, "diggersby", Type.normal, Type.ground),
    ],
    [
        Species(661, "fletchling", Type.normal, Type.flying),
        Species(662, "fletchinder", Type.fire, Type.flying),
        Species(663, "talonflame", Type.fire, Type.flying),
    ],
    [
        Species(664, "scatterbug", Type.bug),
        Species(665, "spewpa", Type.bug),
        Species(666, "vivillon", Type.bug, Type.flying),
    ],
    [
        Species(667, "litleo", Type.fire, Type.normal),
        Species(668, "pyroar", Type.fire, Type.normal),
    ],
    [
        Species(669, "flabebe", Type.fairy),
        Species(670, "floette", Type.fairy),
        Species(671, "florges", Type.fairy),
    ],
    [Species(672, "skiddo", Type.grass), Species(673, "gogoat", Type.grass)],
    [
        Species(674, "pancham", Type.fighting),
        Species(675, "pangoro", Type.fighting, Type.dark),
    ],
    [Species(676, "furfrou", Type.normal)],
    [Species(677, "espurr", Type.psychic), Species(678, "meowstic", Type.psychic)],
    [
        Species(679, "honedge", Type.steel, Type.ghost),
        Species(680, "doublade", Type.steel, Type.ghost),
        Species(681, "aegislash", Type.steel, Type.ghost),
    ],
    [Species(682, "spritzee", Type.fairy), Species(683, "aromatisse", Type.fairy)],
    [Species(684, "swirlix", Type.fairy), Species(685, "slurpuff", Type.fairy)],
    [
        Species(686, "inkay", Type.dark, Type.psychic),
        Species(687, "malamar", Type.dark, Type.psychic),
    ],
    [
        Species(688, "binacle", Type.rock, Type.water),
        Species(689, "barbaracle", Type.rock, Type.water),
    ],
    [
        Species(690, "skrelp", Type.poison, Type.water),
        Species(691, "dragalge", Type.poison, Type.dragon),
    ],
    [Species(692, "clauncher", Type.water), Species(693, "clawitzer", Type.water)],
    [
        Species(694, "helioptile", Type.electric, Type.normal),
        Species(695, "heliolisk", Type.electric, Type.normal),
    ],
    [
        Species(696, "tyrunt", Type.rock, Type.dragon),
        Species(697, "tyrantrum", Type.rock, Type.dragon),
    ],
    [
        Species(698, "amaura", Type.rock, Type.ice),
        Species(699, "aurorus", Type.rock, Type.ice),
    ],
    [Species(701, "hawlucha", Type.fighting, Type.flying)],
    [Species(702, "dedenne", Type.electric, Type.fairy)],
    [Species(703, "carbink", Type.rock, Type.fairy)],
    [
        Species(704, "goomy", Type.dragon),
        Species(705, "sliggoo", Type.dragon),
        Species(706, "goodra", Type.dragon),
    ],
    [Species(707, "klefki", Type.steel, Type.fairy)],
    [
        Species(708, "phantump", Type.ghost, Type.grass),
        Species(709, "trevenant", Type.ghost, Type.grass),
    ],
    [
        Species(710, "pumpkaboo", Type.ghost, Type.grass),
        Species(711, "gourgeist", Type.ghost, Type.grass),
    ],
    [Species(712, "bergmite", Type.ice), Species(713, "avalugg", Type.ice)],
    [
        Species(714, "noibat", Type.flying, Type.dragon),
        Species(715, "noivern", Type.flying, Type.dragon),
    ],
    [Species(716, "xerneas", Type.fairy)],
    [Species(717, "yveltal", Type.dark, Type.flying)],
    [Species(718, "zygarde", Type.dragon, Type.ground)],
    [Species(719, "diancie", Type.rock, Type.fairy)],
    [Species(720, "hoopa", Type.psychic, Type.ghost)],
    [Species(721, "volcanion", Type.fire, Type.water)],
    [
        Species(722, "rowlet", Type.grass, Type.flying),
        Species(723, "dartrix", Type.grass, Type.flying),
        Species(724, "decidueye", Type.grass, Type.ghost),
    ],
    [
        Species(725, "litten", Type.fire),
        Species(726, "torracat", Type.fire),
        Species(727, "incineroar", Type.fire, Type.dark),
    ],
    [
        Species(728, "popplio", Type.water),
        Species(729, "brionne", Type.water),
        Species(730, "primarina", Type.water, Type.fairy),
    ],
    [
        Species(731, "pikipek", Type.normal, Type.flying),
        Species(732, "trumbeak", Type.normal, Type.flying),
        Species(733, "toucannon", Type.normal, Type.flying),
    ],
    [Species(734, "yungoos", Type.normal), Species(735, "gumshoos", Type.normal)],
    [
        Species(736, "grubbin", Type.bug),
        Species(737, "charjabug", Type.bug, Type.electric),
        Species(738, "vikavolt", Type.bug, Type.electric),
    ],
    [
        Species(739, "crabrawler", Type.fighting),
        Species(740, "crabominable", Type.fighting, Type.ice),
    ],
    [Species(741, "oricorio", Type.fire, Type.flying)],
    [
        Species(742, "cutiefly", Type.bug, Type.fairy),
        Species(743, "ribombee", Type.bug, Type.fairy),
    ],
    [Species(744, "rockruff", Type.rock), Species(745, "lycanroc", Type.rock)],
    [Species(746, "wishiwashi", Type.water)],
    [
        Species(747, "mareanie", Type.poison, Type.water),
        Species(748, "toxapex", Type.poison, Type.water),
    ],
    [Species(749, "mudbray", Type.ground), Species(750, "mudsdale", Type.ground)],
    [
        Species(751, "dewpider", Type.water, Type.bug),
        Species(752, "araquanid", Type.water, Type.bug),
    ],
    [Species(753, "fomantis", Type.grass), Species(754, "lurantis", Type.grass)],
    [
        Species(755, "morelull", Type.grass, Type.fairy),
        Species(756, "shiinotic", Type.grass, Type.fairy),
    ],
    [
        Species(757, "salandit", Type.poison, Type.fire),
        Species(758, "salazzle", Type.poison, Type.fire),
    ],
    [
        Species(759, "stufful", Type.normal, Type.fighting),
        Species(760, "bewear", Type.normal, Type.fighting),
    ],
    [
        Species(761, "bounsweet", Type.grass),
        Species(762, "steenee", Type.grass),
        Species(763, "tsareena", Type.grass),
    ],
    [Species(764, "comfey", Type.fairy)],
    [Species(765, "oranguru", Type.normal, Type.psychic)],
    [Species(766, "passimian", Type.fighting)],
    [
        Species(767, "wimpod", Type.bug, Type.water),
        Species(768, "golisopod", Type.bug, Type.water),
    ],
    [
        Species(769, "sandygast", Type.ghost, Type.ground),
        Species(770, "palossand", Type.ghost, Type.ground),
    ],
    [Species(771, "pyukumuku", Type.water)],
    [Species(772, "type-null", Type.normal), Species(773, "silvally", Type.normal)],
    [Species(774, "minior", Type.rock, Type.flying)],
    [Species(775, "komala", Type.normal)],
    [Species(776, "turtonator", Type.fire, Type.dragon)],
    [Species(777, "togedemaru", Type.electric, Type.steel)],
    [Species(778, "mimikyu", Type.ghost, Type.fairy)],
    [Species(779, "bruxish", Type.water, Type.psychic)],
    [Species(780, "drampa", Type.normal, Type.dragon)],
    [Species(781, "dhelmise", Type.ghost, Type.grass)],
    [
        Species(782, "jangmo'o", Type.dragon),
        Species(783, "hakamo'o", Type.dragon, Type.fighting),
        Species(784, "kommo'o", Type.dragon, Type.fighting),
    ],
    [Species(785, "tapu-koko", Type.electric, Type.fairy)],
    [Species(786, "tapu-lele", Type.psychic, Type.fairy)],
    [Species(787, "tapu-bulu", Type.grass, Type.fairy)],
    [Species(788, "tapu-fini", Type.water, Type.fairy)],
    [
        Species(789, "cosmog", Type.psychic),
        Species(790, "cosmoem", Type.psychic),
        Species(791, "solgaleo", Type.psychic, Type.steel),
        Species(792, "lunala", Type.psychic, Type.ghost),
    ],
    [Species(793, "nihilego", Type.rock, Type.poison)],
    [Species(794, "buzzwole", Type.bug, Type.fighting)],
    [Species(795, "pheromosa", Type.bug, Type.fighting)],
    [Species(796, "xurkitree", Type.electric)],
    [Species(797, "celesteela", Type.steel, Type.flying)],
    [Species(798, "kartana", Type.grass, Type.steel)],
    [Species(799, "guzzlord", Type.dark, Type.dragon)],
    [Species(800, "necrozma", Type.psychic)],
    [Species(801, "magearna", Type.steel, Type.fairy)],
    [Species(802, "marshadow", Type.fighting, Type.ghost)],
    [
        Species(803, "poipole", Type.poison),
        Species(804, "naganadel", Type.poison, Type.dragon),
    ],
    [Species(805, "stakataka", Type.rock, Type.steel)],
    [Species(806, "blacephalon", Type.fire, Type.ghost)],
    [Species(807, "zeraora", Type.electric)],
    [Species(808, "meltan", Type.steel)],
    [Species(809, "melmetal", Type.steel)],
    [
        Species(810, "grookey", Type.grass),
        Species(811, "thwackey", Type.grass),
        Species(812, "rillaboom", Type.grass),
    ],
    [
        Species(813, "scorbunny", Type.fire),
        Species(814, "raboot", Type.fire),
        Species(815, "cinderace", Type.fire),
    ],
    [
        Species(816, "sobble", Type.water),
        Species(817, "drizzile", Type.water),
        Species(818, "inteleon", Type.water),
    ],
    [Species(819, "skwovet", Type.normal), Species(820, "greedent", Type.normal)],
    [
        Species(821, "rookidee", Type.flying),
        Species(822, "corvisquire", Type.flying),
        Species(823, "corviknight", Type.flying, Type.steel),
    ],
    [
        Species(824, "blipbug", Type.bug),
        Species(825, "dottler", Type.bug, Type.psychic),
        Species(826, "orbeetle", Type.bug, Type.psychic),
    ],
    [Species(827, "nickit", Type.dark), Species(828, "thievul", Type.dark)],
    [Species(829, "gossifleur", Type.grass), Species(830, "eldegoss", Type.grass)],
    [Species(831, "wooloo", Type.normal), Species(832, "dubwool", Type.normal)],
    [
        Species(833, "chewtle", Type.water),
        Species(834, "drednaw", Type.water, Type.rock),
    ],
    [Species(835, "yamper", Type.electric), Species(836, "boltund", Type.electric)],
    [
        Species(837, "rolycoly", Type.rock),
        Species(838, "carkol", Type.rock, Type.fire),
        Species(839, "coalossal", Type.rock, Type.fire),
    ],
    [
        Species(840, "applin", Type.grass, Type.dragon),
        Species(841, "flapple", Type.grass, Type.dragon),
        Species(842, "appletun", Type.grass, Type.dragon),
        Species(1011, "dipplin", Type.grass, Type.dragon),
        Species(1019, "hydrapple", Type.grass, Type.dragon),
    ],
    [Species(843, "silicobra", Type.ground), Species(844, "sandaconda", Type.ground)],
    [Species(845, "cramorant", Type.flying, Type.water)],
    [Species(846, "arrokuda", Type.water), Species(847, "barraskewda", Type.water)],
    [
        Species(848, "toxel", Type.electric, Type.poison),
        Species(849, "toxtricity", Type.electric, Type.poison),
    ],
    [
        Species(850, "sizzlipede", Type.fire, Type.bug),
        Species(851, "centiskorch", Type.fire, Type.bug),
    ],
    [
        Species(852, "clobbopus", Type.fighting),
        Species(853, "grapploct", Type.fighting),
    ],
    [Species(854, "sinistea", Type.ghost), Species(855, "polteageist", Type.ghost)],
    [
        Species(856, "hatenna", Type.psychic),
        Species(857, "hattrem", Type.psychic),
        Species(858, "hatterene", Type.psychic, Type.fairy),
    ],
    [
        Species(859, "impidimp", Type.dark, Type.fairy),
        Species(860, "morgrem", Type.dark, Type.fairy),
        Species(861, "grimmsnarl", Type.dark, Type.fairy),
    ],
    [Species(868, "milcery", Type.fairy), Species(869, "alcremie", Type.fairy)],
    [Species(870, "falinks", Type.fighting)],
    [Species(871, "pincurchin", Type.electric)],
    [
        Species(872, "snom", Type.ice, Type.bug),
        Species(873, "frosmoth", Type.ice, Type.bug),
    ],
    [Species(874, "stonjourner", Type.rock)],
    [Species(875, "eiscue", Type.ice)],
    [Species(876, "indeedee", Type.psychic, Type.normal)],
    [Species(877, "morpeko", Type.electric, Type.dark)],
    [Species(878, "cufant", Type.steel), Species(879, "copperajah", Type.steel)],
    [Species(880, "dracozolt", Type.electric, Type.dragon)],
    [Species(881, "arctozolt", Type.electric, Type.ice)],
    [Species(882, "dracovish", Type.water, Type.dragon)],
    [Species(883, "arctovish", Type.water, Type.ice)],
    [
        Species(884, "duraludon", Type.steel, Type.dragon),
        Species(1018, "archaludon", Type.steel, Type.dragon),
    ],
    [
        Species(885, "dreepy", Type.dragon, Type.ghost),
        Species(886, "drakloak", Type.dragon, Type.ghost),
        Species(887, "dragapult", Type.dragon, Type.ghost),
    ],
    [Species(888, "zacian", Type.fairy)],
    [Species(889, "zamazenta", Type.fighting)],
    [Species(890, "eternatus", Type.poison, Type.dragon)],
    [
        Species(891, "kubfu", Type.fighting),
        Species(892, "urshifu", Type.fighting, Type.dark),
    ],
    [Species(893, "zarude", Type.dark, Type.grass)],
    [Species(894, "regieleki", Type.electric)],
    [Species(895, "regidrago", Type.dragon)],
    [Species(896, "glastrier", Type.ice)],
    [Species(897, "spectrier", Type.ghost)],
    [Species(898, "calyrex", Type.psychic, Type.grass)],
    [Species(905, "enamorus", Type.fairy, Type.flying)],
    [
        Species(906, "sprigatito", Type.grass),
        Species(907, "floragato", Type.grass),
        Species(908, "meowscarada", Type.grass, Type.dark),
    ],
    [
        Species(909, "fuecoco", Type.fire),
        Species(910, "crocalor", Type.fire),
        Species(911, "skeledirge", Type.fire, Type.ghost),
    ],
    [
        Species(912, "quaxly", Type.water),
        Species(913, "quaxwell", Type.water),
        Species(914, "quaquaval", Type.water, Type.fighting),
    ],
    [Species(915, "lechonk", Type.normal), Species(916, "oinkologne", Type.normal)],
    [Species(917, "tarountula", Type.bug), Species(918, "spidops", Type.bug)],
    [Species(919, "nymble", Type.bug), Species(920, "lokix", Type.bug, Type.dark)],
    [
        Species(921, "pawmi", Type.electric),
        Species(922, "pawmo", Type.electric, Type.fighting),
        Species(923, "pawmot", Type.electric, Type.fighting),
    ],
    [Species(924, "tandemaus", Type.normal), Species(925, "maushold", Type.normal)],
    [Species(926, "fidough", Type.fairy), Species(927, "dachsbun", Type.fairy)],
    [
        Species(928, "smoliv", Type.grass, Type.normal),
        Species(929, "dolliv", Type.grass, Type.normal),
        Species(930, "arboliva", Type.grass, Type.normal),
    ],
    [Species(931, "squawkabilly", Type.normal, Type.flying)],
    [
        Species(932, "nacli", Type.rock),
        Species(933, "naclstack", Type.rock),
        Species(934, "garganacl", Type.rock),
    ],
    [
        Species(935, "charcadet", Type.fire),
        Species(936, "armarouge", Type.fire, Type.psychic),
        Species(937, "ceruledge", Type.fire, Type.ghost),
    ],
    [Species(938, "tadbulb", Type.electric), Species(939, "bellibolt", Type.electric)],
    [
        Species(940, "wattrel", Type.electric, Type.flying),
        Species(941, "kilowattrel", Type.electric, Type.flying),
    ],
    [Species(942, "maschiff", Type.dark), Species(943, "mabosstiff", Type.dark)],
    [
        Species(944, "shroodle", Type.poison, Type.normal),
        Species(945, "grafaiai", Type.poison, Type.normal),
    ],
    [
        Species(946, "bramblin", Type.grass, Type.ghost),
        Species(947, "brambleghast", Type.grass, Type.ghost),
    ],
    [
        Species(948, "toedscool", Type.ground, Type.grass),
        Species(949, "toedscruel", Type.ground, Type.grass),
    ],
    [Species(950, "klawf", Type.rock)],
    [
        Species(951, "capsakid", Type.grass),
        Species(952, "scovillain", Type.grass, Type.fire),
    ],
    [Species(953, "rellor", Type.bug), Species(954, "rabsca", Type.bug, Type.psychic)],
    [Species(955, "flittle", Type.psychic), Species(956, "espathra", Type.psychic)],
    [
        Species(957, "tinkatink", Type.fairy, Type.steel),
        Species(958, "tinkatuff", Type.fairy, Type.steel),
        Species(959, "tinkaton", Type.fairy, Type.steel),
    ],
    [Species(960, "wiglett", Type.water), Species(961, "wugtrio", Type.water)],
    [Species(962, "bombirdier", Type.flying, Type.dark)],
    [Species(963, "finizen", Type.water), Species(964, "palafin", Type.water)],
    [
        Species(965, "varoom", Type.steel, Type.poison),
        Species(966, "revavroom", Type.steel, Type.poison),
    ],
    [Species(967, "cyclizar", Type.dragon, Type.normal)],
    [Species(968, "orthworm", Type.steel)],
    [
        Species(969, "glimmet", Type.rock, Type.poison),
        Species(970, "glimmora", Type.rock, Type.poison),
    ],
    [Species(971, "greavard", Type.ghost), Species(972, "houndstone", Type.ghost)],
    [Species(973, "flamigo", Type.flying, Type.fighting)],
    [Species(974, "cetoddle", Type.ice), Species(975, "cetitan", Type.ice)],
    [Species(976, "veluza", Type.water, Type.psychic)],
    [Species(977, "dondozo", Type.water)],
    [Species(978, "tatsugiri", Type.dragon, Type.water)],
    [Species(984, "great-tusk", Type.ground, Type.fighting)],
    [Species(985, "scream-tail", Type.fairy, Type.psychic)],
    [Species(986, "brute-bonnet", Type.grass, Type.dark)],
    [Species(987, "flutter-mane", Type.ghost, Type.fairy)],
    [Species(988, "slither-wing", Type.bug, Type.fighting)],
    [Species(989, "sandy-shocks", Type.electric, Type.ground)],
    [Species(990, "iron-treads", Type.ground, Type.steel)],
    [Species(991, "iron-bundle", Type.ice, Type.water)],
    [Species(992, "iron-hands", Type.fighting, Type.electric)],
    [Species(993, "iron-jugulis", Type.dark, Type.flying)],
    [Species(994, "iron-moth", Type.fire, Type.poison)],
    [Species(995, "iron-thorns", Type.rock, Type.electric)],
    [
        Species(996, "frigibax", Type.dragon, Type.ice),
        Species(997, "arctibax", Type.dragon, Type.ice),
        Species(998, "baxcalibur", Type.dragon, Type.ice),
    ],
    [
        Species(999, "gimmighoul", Type.ghost),
        Species(1000, "gholdengo", Type.steel, Type.ghost),
    ],
    [Species(1001, "wo-chien", Type.dark, Type.grass)],
    [Species(1002, "chien-pao", Type.dark, Type.ice)],
    [Species(1003, "ting-lu", Type.dark, Type.ground)],
    [Species(1004, "chi-yu", Type.dark, Type.fire)],
    [Species(1005, "roaring-moon", Type.dragon, Type.dark)],
    [Species(1006, "iron-valiant", Type.fairy, Type.fighting)],
    [Species(1007, "koraidon", Type.fighting, Type.dragon)],
    [Species(1008, "miraidon", Type.electric, Type.dragon)],
    [Species(1009, "walking-wake", Type.water, Type.dragon)],
    [Species(1010, "iron-leaves", Type.grass, Type.psychic)],
    [
        Species(1012, "poltchageist", Type.grass, Type.ghost),
        Species(1013, "sinistcha", Type.grass, Type.ghost),
    ],
    [Species(1014, "okidogi", Type.poison, Type.fighting)],
    [Species(1015, "munkidori", Type.poison, Type.psychic)],
    [Species(1016, "fezandipiti", Type.poison, Type.fairy)],
    [Species(1017, "ogerpon", Type.grass)],
    [Species(1020, "gouging-fire", Type.fire, Type.dragon)],
    [Species(1021, "raging-bolt", Type.electric, Type.dragon)],
    [Species(1022, "iron-boulder", Type.rock, Type.psychic)],
    [Species(1023, "iron-crown", Type.steel, Type.psychic)],
    [Species(1024, "terapagos", Type.normal)],
    [Species(1025, "pecharunt", Type.poison, Type.ghost)],
]
